### ISSUE TITLE
Axios network error

### ISSUE THREAD

**Issue by mzavattaro** [WebDevSimplified/react-query-crash-course-example#1]
Git cloned this repo to see how React Query works behind the scenes. However the repo throws an error when creating a new post. 

To reproduce:
1. Clone the repo
2. cd into client
3. npm install
4. npm run dev
5. Navigate to http://localhost:5173/

Error:
```{"message":"Network Error","name":"AxiosError","stack":"AxiosError: Network Error\n at XMLHttpRequest.handleError (http://localhost:5173/node_modules/.vite/deps/axios.js?v=6a2c566a:1365:14)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"env":{},"headers":{"Accept":"application/json, text/plain, */*"},"params":{"_sort":"title"},"method":"get","url":"http://localhost:3000/posts"},"code":"ERR_NETWORK","status":null}```

**Comment by WebDevSimplified** [comment]
I just added a README that explains how to run this project.

Essentially, you need to also run the API that this project connects to as well.
